// This file is automatically generated by Firebase Studio. Do not edit.

// Follow the instructions in the Firebase console to get your config object.
// https://firebase.google.com/docs/web/setup#get-config

export const firebaseConfig = {
  apiKey: "AIzaSyA_...real-key-placeholder",
  authDomain: "infinite-chat.firebaseapp.com",
  projectId: "infinite-chat",
  storageBucket: "infinite-chat.appspot.com",
  messagingSenderId: "123456789012",
  appId: "1:123456789012:web:1234567890abcdef",
  databaseURL: "https://infinite-chat.firebaseio.com",
};
