// This file is automatically generated by Firebase Studio. Do not edit.

// Follow the instructions in the Firebase console to get your config object.
// https://firebase.google.com/docs/web/setup#get-config

export const firebaseConfig = {
  apiKey: "PASTE_YOUR_API_KEY_HERE",
  authDomain: "infinite.firebaseapp.com",
  projectId: "infinite",
  storageBucket: "infinite.appspot.com",
  messagingSenderId: "PASTE_YOUR_SENDER_ID_HERE",
  appId: "PASTE_YOUR_APP_ID_HERE",
  databaseURL: "https://infinite.firebaseio.com",
};
